name: priceprediction

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http:
  get:
  google_fonts:
  flutter_screenutil:
  intl:
  carousel_slider: ^5.0.0
  firebase_core: ^3.12.1
  firebase_auth:
  font_awesome_flutter:
  google_nav_bar:
  line_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/


  fonts:
    - family: grenda
      fonts:
        - asset: assets/fonts/grenda.ttf
          style: normal
    - family: quicksand
      fonts:
        - asset: assets/fonts/quicksand.ttf
          style: normal
